import { intentDefinition, type PublishedRecord } from "@dig/core";
import { fieldLabel, INTENT_LABELS, type CollectionBlueprint, type IntentId } from "@dig/schemas";

/*
  Written report for a dataset version of any live intent, as Markdown. Everything in it is derived from the
  stored version: the ranked records, the score components the pipeline saved on each one, the evidence
  quotes, and the conflicts raised by the run that produced the version. Nothing is generated by an LLM.
*/

/** The activity-score weights. These mirror scoreRecord() in packages/core/src/rank.ts. */
const ACTIVITY_WEIGHTS = { recency: 0.4, sourceCount: 0.2, officialSource: 0.2, freshness: 0.2 } as const;

/** Per-intent wording: what one record is, and what "active" means for it. */
const NOUNS: Partial<Record<IntentId, { many: string; activity: string; limits: string[] }>> = {
  SPONSOR_LOOKUP: {
    many: "sponsors",
    activity: "how recently and how credibly the web shows them sponsoring",
    limits: [
      "**Location is not filtered.** Sponsors based outside the requested country are kept on purpose — many sponsor and mentor remotely.",
      "**Sponsorship type is the page's own wording**, so it varies between events (for example “Title Sponsor” vs “Gold Partner”).",
    ],
  },
  JOB_LOOKUP: {
    many: "open roles",
    activity: "how recently and how widely each role is listed",
    limits: [
      "**Job boards:** Wellfound, Y Combinator's Work at a Startup, Instahyre, Cutshort, Internshala and the open web. LinkedIn is not searched — it needs a login.",
      "**A listing can close at any time.** Re-run the search before applying; roles that disappear show up as dropped in the diff.",
    ],
  },
  LEAD_LOOKUP: {
    many: "leads",
    activity: "how recently and how credibly each company is named as fitting the target",
    limits: [
      "**Contacts come from each company's own website** (published inboxes and phone numbers), never guessed or pattern-generated.",
      "**Volume is deliberately modest** — fewer, verifiable companies rather than a long unverified list.",
    ],
  },
  COMPETITOR_LOOKUP: {
    many: "competitors",
    activity: "how recently and how often each product is named as a competitor or alternative",
    limits: [
      "**Sources include review sites, YouTube and Instagram.** Social posts give names and pricing claims in the creator's own words; check the official site before quoting a price.",
      "**Pricing signals are quoted as written** and can go stale quickly.",
    ],
  },
  JUDGE_LOOKUP: {
    many: "judges and mentors",
    activity: "how recently and how credibly each person is shown judging, mentoring or working in the field",
    limits: [
      "**Sources include past event pages and Google Scholar profiles.** Being listed doesn't mean someone is available — reach out before announcing anyone.",
      "**Emails are shown only when published on the source page.**",
    ],
  },
};

const HIDDEN_FIELDS = new Set(["source_url", "last_verified"]);

interface ReportConflict {
  label?: string;
  field: string;
  oldValue: string;
  newValue: string;
  status: string;
  reason: string | null;
}

export interface ReportInput {
  job: { name: string; query: string; blueprint: CollectionBlueprint };
  version: { versionNumber: number; createdAt: string; qualityScore: number | null; avgConfidence: number | null };
  records: PublishedRecord[];
  conflicts: ReportConflict[];
  now?: Date;
}

export function renderReport(input: ReportInput): string {
  const { job, version, records } = input;
  const now = input.now ?? new Date();
  const strategy = job.blueprint.ranking.strategy;
  const definition = intentDefinition(job.blueprint.intent);
  const noun = NOUNS[job.blueprint.intent] ?? { many: "records", activity: "how recently and credibly each record is sourced", limits: [] };
  const primary = definition.primaryField;
  const name = (record: PublishedRecord) => record.fields[primary] || record.fields.company_name || record.canonicalEntityId;
  const columns = definition.fields.filter((field) => !HIDDEN_FIELDS.has(field));
  const detailFields = columns.filter((field) => field !== primary);
  const contactFields = ["email", "phone", "contact", "website", "profile_url"].filter((field) => definition.fields.includes(field));
  const sources = citationIndex(records);
  const cite = (url: string | undefined) => (url && sources.has(url) ? `[${sources.get(url)!.n}]` : "");
  const citeAll = (record: PublishedRecord) =>
    [...new Set(record.sources.map((source) => source.url))].map(cite).filter(Boolean).join("");

  const pending = input.conflicts.filter((conflict) => conflict.status === "PENDING");
  const auto = input.conflicts.filter((conflict) => conflict.status === "AUTO_RESOLVED");
  const best = (record: PublishedRecord) => bestAuthority(record);
  const count = (predicate: (record: PublishedRecord) => boolean) => records.filter(predicate).length;
  const domains = new Set([...sources.values()].map((source) => source.domain));
  const statusCounts = tally(records.map((record) => STATUS_LABELS[record.status] ?? record.status));

  const out: string[] = [];
  out.push(`# ${INTENT_LABELS[job.blueprint.intent]} report — ${job.name}`, "");
  out.push(
    `> **Query:** “${job.query}”  `,
    `> **Intent:** ${INTENT_LABELS[job.blueprint.intent]} · **Ranking strategy:** \`${strategy}\`  `,
    `> **Dataset:** version ${version.versionNumber}, collected ${fmtDate(version.createdAt)} · **Report generated:** ${fmtDate(now.toISOString())}`,
    "",
  );

  out.push("## Summary", "");
  out.push(
    `- **${records.length} ${noun.many}**, backed by **${sources.size} source pages** on **${domains.size} sites**.`,
    `- **Best source per record:** ${count((r) => best(r) === "official")} official pages, ${count((r) => best(r) === "press")} press, ${count((r) => best(r) === "secondary")} secondary listings.`,
    `- **Corroboration:** ${count((r) => r.sourceCount >= 2)} records (${pct(count((r) => r.sourceCount >= 2), records.length)}) are confirmed by two or more pages.`,
    ...(contactFields.length
      ? [`- **Coverage:** ${contactFields.map((field) => `${count((r) => Boolean(r.fields[field]))} with ${fieldLabel(field).toLowerCase()}`).join(", ")}.`]
      : []),
    `- **Status:** ${Object.entries(statusCounts).map(([label, n]) => `${n} ${label.toLowerCase()}`).join(", ")}.`,
    `- **Conflicts from this run:** ${pending.length} waiting for your review, ${auto.length} resolved automatically.`,
  );
  if (version.qualityScore !== null || version.avgConfidence !== null) {
    out.push(
      `- **Dataset quality:** ${version.qualityScore !== null ? `${Math.round(version.qualityScore)}/100` : "—"}, average record confidence ${version.avgConfidence !== null ? version.avgConfidence.toFixed(2) : "—"}.`,
    );
  }
  const leaders = records.slice(0, 5).map((record) => `**${name(record)}**`);
  if (leaders.length) out.push(`- **Top of the list:** ${leaders.join(", ")}.`);
  out.push("");

  out.push("## How the list is ranked", "");
  out.push(
    `${noun.many[0]!.toUpperCase()}${noun.many.slice(1)} are ordered by an **activity score**: ${noun.activity}. ` +
      "A result named on a fresh, official page — and confirmed by more than one page — ranks above one that appears once on an old third-party listing.",
    "",
  );
  out.push(
    "```",
    `activity = ${ACTIVITY_WEIGHTS.recency} × recency + ${ACTIVITY_WEIGHTS.sourceCount} × corroboration + ${ACTIVITY_WEIGHTS.officialSource} × source authority + ${ACTIVITY_WEIGHTS.freshness} × freshness`,
    "```",
    "",
    "| Signal | Weight | What it measures |",
    "|---|---|---|",
    `| Recency | ${ACTIVITY_WEIGHTS.recency} | Age of the newest page naming the sponsor: 1 − days ÷ 200, so 1.0 for a page published today, never below 0.15 (reached at 170 days). A page with no publication date scores 0.40. |`,
    `| Corroboration | ${ACTIVITY_WEIGHTS.sourceCount} | Independent pages naming it: 1 page = 0.45, 2 pages = 0.75, 3 or more = 1.0. |`,
    `| Source authority | ${ACTIVITY_WEIGHTS.officialSource} | Best page type: official event/company page = 1.0, press = 0.74, secondary listing = 0.62. |`,
    `| Freshness | ${ACTIVITY_WEIGHTS.freshness} | How recently Dig verified the record, against this search's ${job.blueprint.freshness.maxAgeDays}-day freshness window. |`,
    "",
    "Ties are broken by **record confidence** (source authority 0.35, corroboration 0.25, freshness 0.2, extraction quality 0.2), then alphabetically. " +
      "Confidence does not move a record up on its own — it only separates sponsors with equal activity.",
    "",
  );
  const withDates = records.map((record) => newestDays(record, now)).filter((days): days is number => days !== null);
  if (withDates.length === 0) {
    out.push(
      `**In this dataset:** none of the ${sources.size} source pages states a publication date, so every record gets the same recency (0.40). ` +
        `The order is therefore decided by corroboration, source authority and freshness — ${noun.many} confirmed by several pages, including an official one, rise to the top.`,
      "",
    );
  } else {
    if (withDates.length < records.length) {
      out.push(`${records.length - withDates.length} of ${records.length} records have no dated source and get the default recency of 0.40.`, "");
    }
    out.push(
      `In this dataset, the newest source for a typical record (median) is **${median(withDates)} days old**, and ` +
        `${pct(count((r) => (newestDays(r, now) ?? Infinity) <= 90), records.length)} of records have a source from the last 90 days.`,
      "",
    );
  }

  out.push("## Top 10, and why they rank there", "");
  for (const record of records.slice(0, 10)) {
    const parts = record.activityComponents;
    const second = detailFields.find((field) => record.fields[field]);
    out.push(`### #${record.rank} ${name(record)}${second ? ` — ${record.fields[second]}` : ""}`, "");
    out.push(
      `- **Activity ${record.activityScore.toFixed(2)}** = 0.4 × ${parts.recency.toFixed(2)} recency + 0.2 × ${parts.sourceCount.toFixed(2)} corroboration + 0.2 × ${parts.officialSource.toFixed(2)} authority + 0.2 × ${parts.freshness.toFixed(2)} freshness · confidence ${record.confidence.toFixed(2)}`,
      `- **Why:** ${whyRanked(record, now)}`,
    );
    for (const field of detailFields) {
      const value = record.fields[field];
      if (!value || field === second) continue;
      out.push(`- **${fieldLabel(field)}:** ${value} ${cite(evidenceFor(record, field)?.sourceUrl)}`.trimEnd());
    }
    const quote = evidenceFor(record, primary);
    if (quote) out.push(`- **Evidence:** “${snippet(quote.excerpt, quote.value)}” ${cite(quote.sourceUrl)}`);
    out.push(`- **Sources:** ${citeAll(record) || "—"}`, "");
  }

  out.push("## Full results", "");
  out.push(`| # | ${columns.map(fieldLabel).join(" | ")} | Activity | Confidence | Sources |`, `|${"---|".repeat(columns.length + 4)}`);
  for (const record of records) {
    const cells = columns.map((field) => cell(field === primary ? name(record) : record.fields[field]));
    out.push(`| ${record.rank} | ${cells.join(" | ")} | ${record.activityScore.toFixed(2)} | ${record.confidence.toFixed(2)} | ${citeAll(record) || "—"} |`);
  }
  out.push("");

  out.push("## Conflicts from this run", "");
  if (input.conflicts.length === 0) out.push("No values changed in a way that needed a decision.", "");
  for (const [title, list] of [
    ["Waiting for your review", pending],
    ["Resolved automatically", auto],
  ] as const) {
    if (list.length === 0) continue;
    out.push(`**${title}**`, "");
    for (const conflict of list) {
      out.push(`- **${conflict.label ?? "Record"}** — ${conflict.field}: “${conflict.oldValue || "—"}” → “${conflict.newValue || "—"}”${conflict.reason ? `. ${conflict.reason}` : ""}`);
    }
    out.push("");
  }

  out.push("## Sources", "");
  for (const [url, source] of sources) {
    out.push(
      `${source.n}. [${escapeLink(source.title || source.domain)}](${url}) — ${source.authority}${source.publishedAt ? `, published ${fmtDate(source.publishedAt)}` : ""} · cited by ${source.records} record${source.records === 1 ? "" : "s"}`,
    );
  }
  out.push("");

  out.push("## Method and limitations", "");
  out.push(
    "- **Grounded, not generated.** Every field is kept only if it appears word for word (ignoring case) on the page it cites. Values that can't be quoted from a source are dropped rather than guessed.",
    `- **Where the data comes from.** Dig searched the live web, read each page's text, and kept only ${noun.many} and details it could quote from that text.`,
    ...noun.limits.map((line) => `- ${line}`),
    "- **Publication dates** come from the source pages when they state one; pages without a date count as older, which lowers their recency.",
    "",
  );
  return out.join("\n");
}

const STATUS_LABELS: Record<string, string> = {
  verified: "Verified",
  needs_review: "Need review",
  possible_duplicate: "Possible duplicates",
  incomplete: "Incomplete",
};

function citationIndex(records: PublishedRecord[]) {
  const index = new Map<string, { n: number; title: string; domain: string; authority: string; publishedAt: string; records: number }>();
  for (const record of records) {
    for (const url of new Set(record.sources.map((source) => source.url))) {
      const source = record.sources.find((item) => item.url === url)!;
      const entry = index.get(url);
      if (entry) entry.records += 1;
      else index.set(url, { n: index.size + 1, title: source.title, domain: source.domain, authority: source.authority, publishedAt: source.publishedAt, records: 1 });
    }
  }
  return index;
}

function bestAuthority(record: PublishedRecord) {
  const kinds = record.sources.map((source) => source.authority);
  return kinds.includes("official") ? "official" : kinds.includes("press") ? "press" : "secondary";
}

function newestDays(record: PublishedRecord, now: Date): number | null {
  const newest = Math.max(...record.sources.map((source) => Date.parse(source.publishedAt)).filter((time) => !Number.isNaN(time)));
  if (!Number.isFinite(newest)) return null;
  return Math.max(0, Math.round((now.getTime() - newest) / 86_400_000));
}

function whyRanked(record: PublishedRecord, now: Date): string {
  const days = newestDays(record, now);
  const official = record.sources.find((source) => source.authority === "official");
  const reasons = [
    days === null ? "no dated source, so recency is scored low" : days <= 30 ? `named on a page published ${days} days ago` : `newest source is ${days} days old`,
    record.sourceCount >= 2 ? `confirmed by ${record.sourceCount} separate pages` : "found on a single page",
    official ? `backed by an official page (${official.domain})` : `best source is ${bestAuthority(record)} (${record.sources[0]?.domain ?? "unknown"})`,
  ];
  return `${reasons.join("; ")}.`;
}

function evidenceFor(record: PublishedRecord, field: string) {
  const value = record.fields[field];
  const forField = record.evidence.filter((item) => item.fieldName === field);
  return forField.find((item) => value && item.excerpt.toLowerCase().includes(value.toLowerCase())) ?? forField[0];
}

function snippet(excerpt: string, value: string) {
  const flat = excerpt.replace(/\s+/g, " ").trim();
  const at = flat.toLowerCase().indexOf(value.toLowerCase());
  if (at < 0) return flat.slice(0, 180) + (flat.length > 180 ? "…" : "");
  const start = Math.max(0, at - 80);
  const end = Math.min(flat.length, at + value.length + 80);
  return `${start > 0 ? "…" : ""}${flat.slice(start, end)}${end < flat.length ? "…" : ""}`.replace(/[“”]/g, '"');
}

function cell(value: string | undefined) {
  return value ? value.replace(/\|/g, "\\|").replace(/\s+/g, " ") : "—";
}

function escapeLink(text: string) {
  return text.replace(/[[\]]/g, "").replace(/\s+/g, " ").trim();
}

function tally(values: string[]) {
  const counts: Record<string, number> = {};
  for (const value of values) counts[value] = (counts[value] ?? 0) + 1;
  return counts;
}

function median(values: number[]) {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)] ?? 0;
}

function pct(part: number, whole: number) {
  return whole ? `${Math.round((part / whole) * 100)}%` : "0%";
}

function fmtDate(iso: string) {
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? iso : date.toISOString().slice(0, 10);
}
